### ISSUE TITLE
Code style check and auto-format with node-jscs

### ISSUE THREAD

**Issue by isusanin** [soliton4/nodeMirror#18]
This is a feature request to have automatic code style checking and auto-formatting in the JS file editor that node-jscs can provide.

**Comment by soliton4** [comment]
i am willing to implement this.
you mention it has a format feature, but in the docs and demos i only see error/ warning reporting when the code does not comply with the preset.
can you give me some pointers how to use it to format code?

**Comment by isusanin** [comment]
Check this out. I'm not sure if they're using auto-format from jscs or implemented their own.
http://zz85.github.io/mrdoobapproves/

**Comment by soliton4** [comment]
i am pretty excited about the formatter feature, simple linting allready exists.
if you need the jscs linting as an alternative i can implement it.

**Comment by soliton4** [comment]
@isusanin i figured out where @zz85 got his formatter from.
a first test is available:
https://github.com/soliton4/nodeMirror/commit/9389d26ef4dcdf5d610cba130335cde53b22584e

just get the latest dev version
https://github.com/soliton4/nodeMirror/wiki/installing-from-github

for javascript files there is a format button.
since i dont know what jscs can do i simply copied the formatting options from @zz85

give it a try, tell me what features would be good to enable / put in configuration.

do you still have need for the linting option?

cheers and good n8

**Comment by isusanin** [comment]
@soliton4 Wow! Thank you! That worked pretty well! I'm really impressed with how quickly you got the change in. I wonder if other styles besides "mdcs" can be supported. I guess I'll play with that later. Cheers!

**Comment by soliton4** [comment]
@isusanin well it is a neat feature. i kinda allways wanted a formatting option.

could you tell me what configuration options make sense for it?
you seem to be more familiar with the lib.

btw where are you from. email me

**Comment by isusanin** [comment]
I'm not that familiar with the library, but from what I've learned is that it is kind of a spin-off from jsHint with a focus on code style. It's supposed to complement jsHint. It would be nice to have it even further integrated to add its code-style warnings, but that would be a separate feature request. As far as configuration goes, JSCS has a few useful presets: "airbnb", "crockford", "google", "jquery", "mdcs", "wikimedia", "yandex". Right now, you're using "mdcs", but a setting somewhere to chose any one of the 7 would be nice. However, I'm not sure if the auto-format code you're pulling supports anything besides "mdcs". If not, it should come soon as there seems to be progress on node-jscs "Auto formatting API and option. [$200]" issue.

**Comment by soliton4** [comment]
tell you what, im gonna make a settings menu for it and you give me feedback what works and what not.

isnt jsHint a spinoff of jsLint? guess one has to expect lots of forks when it comes to coding style ;p

i am actually using jsHint for syntax check in nodeMirror. check the syntax check button.
using jscs as addition or alternative would be easy.

i am also planning a auto auto format. that formats a js file the moment you open it. so you dont need to argue about coding guide, just let the ide take care of it for you.

**Comment by isusanin** [comment]
I'll try out the settings menu as soon as it's ready. Thanks!

I read that jsHint committers didn't want to include code-style/formatting rules in jsHint and gave birth to JSCS instead to focus on that. The two can work together.

I'm not sure about the auto format on file open. I think it would be too invasive. For one, it can fail if the code has syntax errors. Second, if it's somebody else's file, you don't necessarily want to impose your code-style on it after saving. Remember, the file might be viewed in other IDEs that don't have auto-formatting. That being said, for read-only files it might be useful to have a feature for "view formatted".

**Comment by gero3** [comment]
It doesn't change the code if it has syntax errors. 
It also doesn't have support for anything more then MDCS for the moment but it is just a matter of editing the rules to add the formatting code.

**Comment by soliton4** [comment]
i integrated a config for jscs
you can now use jscs as linter 
and you can config what preset is used

i also created a auto formater

https://github.com/soliton4/nodeMirror/commit/a9014cc1b9c365acdb3115a43c506eecdeda38d5

you must update the submodules as well since one of the neccessary commits is:

https://github.com/soliton4/sol-amd/commit/a06ff4e94574fa22abcd5c7f8f19e021276a220b

i hope it gets pulled when you do
git submodule update

**Comment by soliton4** [comment]
ps: let me know what you think.
check if everything is working as you would expect.

and give me some hints for the gui. the menu gets fuller and fuller and i dont know what to do about it

**Comment by isusanin** [comment]
It looks very good! Formatting seems to only work with "mdcs" for now, but that's OK. I think the addition of JSCS warnings is great!
As far as menu clutter is is concerned, I have a few ideas.
One thing you can do is eliminate "Check Syntax" button by reorganizing the "Format cfg." menu. I would also rename the manu to "JS Settings"
-------- JS Settings ---------
Check Syntax with JSHint [x]
Check Style with JSCS [x]
JSCS style preset [dropdown]
Format on open [x]

A few other things you can do is replace a bunch of text buttons with small icons with tool-tips, and/or organize everything into hierarchical menus.

What do you think?

**Comment by soliton4** [comment]
i tested with crockford and it did "something"

remember that nodeMirror is not a js only ide
there are syntax checks for css, json and promiseland but i could make a custom menu for each

i am thankful for the input, however since you seem to be a frontend compatible guy, dont you wanna just  create some icons?
i literaly have no problem with contributors going crazy on the frontend.

remember that nodeMirror is bsd so commercial icons could be a problem

**Comment by isusanin** [comment]
Right, but each type of file may have settings specific to it.
When you open a JS file, "JS Settings" menu appears, when you open a promiseland file, a "PL Settings" menu appears.
I'm sure we can find some creative commons icons. I'll take a look.

**Comment by soliton4** [comment]
yeah thats pretty much what i had in mind

or a settings dlg that is different for each type. would save space but can also be confusing.

**Comment by soliton4** [comment]
@isusanin so can we close this issue and open a new one for design stuff?

**Comment by isusanin** [comment]
Yes, I'm closing this issue. Auto-format will be enhanced at a later point I imagine when JSCS team completes the comprehensive implementation.
